gcivil-nyu-org/wed-fall24-team5

.github/workflows/lint.yml, README.md, src/accounts/apps.py, src/accounts/templates/accounts/login.html, src/accounts/templates/accounts/profile.html, src/accounts/templates/accounts/register.html, src/accounts/tests.py, src/accounts/urls.py, src/accounts/views.py, src/django_management/settings.py, src/django_management/urls.py, src/templates/base.html
- Create the accounts app
- Define URL patterns for the accounts app
- Add routes for login, registration, logout, and profile management in accounts/urls.py.
- Include the accounts URL patterns in the main urls.py file.
- Set up templates:
- Create templates for login (login.html), registration (register.html), and profile management (profile.html) in accounts/templates/accounts/.
- Ensure the templates inherit from the base template (base.html)
- Ensure root URL redirects to the login page:
- Update the main urls.py to redirect the root URL (/) to the login page.
- Test the accounts app:
- Verify that login, registration, and logout functionality works as expected.
=> Feature/issue 49/initial accounts setup

src/accounts/templates/accounts/login.html, src/accounts/templates/accounts/register.html, src/static/css/style.css, src/templates/base.html, src/templates/partials/footer.html, src/templates/partials/header.html
- Add header logic to show different content for non-authenticated vs authenticated users.
- Non-authenticated users will only the logo and Login and Register buttons.
- Authenticated users will see Dashboard, Orders, Profile, and a View As dropdown in which they can switch to organization views. The Login and Register buttons will change to Messages and Logout.
=> Feature/issue 51/header logic

.coveralls.yml, .travis.yml, README.md
- Updates Travis for `coveralls` fix. 
- Added Postgres to Travis environment
=> [DRAFT] Bugfix/issue 73/deploy to aws with travis

src/accounts/adapters.py, src/django_management/settings.py, src/donor_dashboard/admin.py, src/donor_dashboard/apps.py, src/donor_dashboard/models.py, src/donor_dashboard/tests.py, src/donor_dashboard/views.py
Created an app for donor dashboard
- None
=> Create app for donor dashboard

.travis.yml, src/recipient_dashboard/tests.py
Implement unit test cases for list donations on recipient dashboard functionality
- 🧪 Test
- Might have merge conflicts with https://github.com/gcivil-nyu-org/wed-fall24-team5/pull/85
=> Test/issue 81/view list of all donations

src/accounts/templates/accounts/login.html
- Hotfix to fix log in page not loading (doubling of page title attribute)
=> login page bug fix

src/templates/_base.html
=> force light mode, no dark mode

src/accounts/templates/accounts/login.html, src/accounts/templates/accounts/register.html, src/donor_dashboard/templates/add_organization.html, src/donor_dashboard/templates/donor_dashboard/list.html, src/recipient_dashboard/templates/recipient_dashboard/dashboard.html
- Has fields wrap if fields are too long in cards
- Optimizes better for mobile.
=> reformatting for long fields

src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/urls.py, src/donor_dashboard/views.py
View donations in manage organization page
Add UI buttons to delete donation,manage donations, delete organization, manage organizations details
- None
=> View donations in manage organization page

src/donor_dashboard/templates/donor_dashboard/list.html
Fixed organization details on the donor dashboard which are currently not being displayed
=> Fixed organization details on the donor dashboard

src/accounts/templates/accounts/login.html, src/accounts/templates/accounts/register.html, src/accounts/views.py, src/recipient_dashboard/templates/recipient_dashboard/dashboard.html, src/recipient_dashboard/views.py, src/static/js/notifications.js, src/templates/_base.html, src/templates/partials/notifications.html
- Implement search functionality
- Enables limiting search to food or organization
- Enables filtering search by organization type
- Enables filtering search by quantity
- Add clear all button
=> Feature/Issue 42/search by type and category

src/donor_dashboard/templates/donor_dashboard/list.html, src/donor_dashboard/views.py
Added delete organization functionality in the manage organization page.
- None
=> Feature/issue 34/delete organization

src/donor_dashboard/templates/donor_dashboard/list.html, src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/templates/donor_dashboard/organization_details.html, src/donor_dashboard/urls.py, src/donor_dashboard/views.py
Added a page to modify organization details.
- Merge after https://github.com/gcivil-nyu-org/wed-fall24-team5/pull/109
=> Feature/issue 33/modify organization details

src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/urls.py, src/donor_dashboard/views.py, src/static/js/manage_organization.js
=> Feature/issue 39/delete donation as donor of a specific organization

src/recipient_dashboard/tests.py
Add tests for search and filter function in recipient dashboard.
- Merge #123 first
=> Test/issue 42/search filter tests

src/recipient_dashboard/tests.py
Quick fix to support test run in new databases for view recipient dashboard. A few tests are failing in Travis but not in Local, since these tests are using the old database definitions. This fix will cause tests to pass in Travis ! Not sure why local isn't catching these as a failure.
- Unblocks https://github.com/gcivil-nyu-org/wed-fall24-team5/pull/108
=> updates to tests to support new DB

src/donor_dashboard/templates/donor_dashboard/list.html, src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/templates/donor_dashboard/organization_details.html, src/donor_dashboard/urls.py, src/donor_dashboard/views.py, src/static/js/org_list_tabs.js
Modified the delete organization flow, which is
- Makes all the reservations inactive
- Makes all the donations inactive
- Makes the organization inactive
- None
=> Feature/issue 34/new delete organization flow

src/donor_dashboard/templates/donor_dashboard/list.html, src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/templates/donor_dashboard/organization_details.html, src/donor_dashboard/tests.py, src/donor_dashboard/urls.py, src/donor_dashboard/views.py, src/static/js/org_list_tabs.js
Added tests for donor dashboard
- Merge after https://github.com/gcivil-nyu-org/wed-fall24-team5/pull/122
=> Test/issue 24/tests for donor dashboard

src/donor_dashboard/tests.py
Implemented test cases for Add Donation functionality
=> Implemented test cases for Add Donation functionality

src/donor_dashboard/tests.py
Implemented tests for modify donation functionality
- PR for implementing tests for add donation functionality needs to be merged first and then this needs to be merged
=> Implemented tests for modify donation functionality

src/database/tests.py
Added testing for Database, Models.py ORM functionality, with custom teardown to make sure we are not deleting anything we didn't want to delete from the database.
No dependencies, should run in Travis without issues.
=> Add testing of ORM functionality with proper teardown.

src/database/tests.py, src/donor_dashboard/tests.py
- Implement tests for delete donation functionality
- Added a case to check for unsuccessful GET request for Add Donation
- Code documentation
=> Implement tests for delete donation functionality and code documentation

src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/views.py
Fixed the bug for add and modify functionalities
=> Fixed the bug for add and modify functionalities

src/database/models.py, src/database/tests.py
Fix tests.py for database
No dependancies.
=> Bugfix/issue 136/fix database tests

src/donor_dashboard/templates/donor_dashboard/list.html, src/static/js/add_org.js
Make add organization as pop-up in donor dashboard
- None
=> Feature/issue 143/make add organization as pop up

src/donor_dashboard/tests.py
Implement additional test cases for add donations
=> Implement additional test cases for add donations

.travis.yml, README.md
Slight readme updates to reflect the new application layout. Also this will trigger a new build on `Develop` so it is no longer displaying failure !
=> Chore/issue 00/readme updates

src/recipient_dashboard/templates/recipient_dashboard/dashboard.html, src/recipient_dashboard/views.py, src/templates/_base.html
- Add in an organization's average stars to the recipient dashboard.
=> Add in stars to recipient dashboard

src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/views.py, src/static/js/manage_organization.js, src/templates/_base.html
- Refactor the manage organization view so that it has tabs.
- Add in the ability to display reviews to an organization
=> Feature/issue 19/organizations view reviews

src/django_management/asgi.py, src/django_management/settings.py, src/django_management/urls.py, src/messaging/admin.py, src/messaging/apps.py, src/messaging/models.py, src/messaging/tests.py, src/messaging/urls.py, src/messaging/views.py
Messaging custom app added so that Akhil and I can collaborate for the messaging functionality implementation
=> Messaging custom app added

.ebextensions/02_websocket.config
=> listen port to 80

.ebextensions/02_websocket.config, src/messaging/templates/messaging_dashboard.html
Config to setup web socket in elastic beanstalk 
- None
=> Bugfix/issue 30/config to setup websocket in elasticbeanstalk new

.ebextensions/02_websocket.config, src/messaging/templates/messaging_dashboard.html
Config to setup web socket in elastic beanstalk latest
- None
=> Bugfix/issue 30/config to setup websocket in elasticbeanstalk latest

src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/views.py, src/static/css/manage_organization.css, src/static/js/manage_organization.js
- Improves Review UI to group by donation.
=> Chore/issue 175/updates to review UI

src/donor_dashboard/templates/donor_dashboard/list.html
Fix title overflowing on organization list page.
=> Bugfix/issue 212/fix overflowing organization titles

Procfile
=> procfile to run daphne

.travis.yml, src/django_management/settings.py
- Sets up a deployment cycle for the `test` branch
- Sets up a new AWS Environment for the `test` branch
- Adds the new AWS environment into allowed URLs
- Will require creation of the `test` branch for deployment
=> Chore/issue 218/new aws instance for testing

Procfile, requirements.txt, src/django_management/settings.py
Replace this with a summary of your changes including any high-level business or decision-making context.
- 🌐 Release (for preparing a release branch)
- 🔄 Refactor (for code refactoring and tech debt)
- Call out here if this is dependent on another Pull Request, and paste the link if possible
- This branch contains a breaking change ⚠️
=> Test messaging

Procfile, src/django_management/asgi.py
Replace this with a summary of your changes including any high-level business or decision-making context.
- 🌐 Release (for preparing a release branch)
- 🔄 Refactor (for code refactoring and tech debt)
- Call out here if this is dependent on another Pull Request, and paste the link if possible
- This branch contains a breaking change ⚠️
=> remove procfile

Procfile, src/django_management/asgi.py, src/messaging/consumers.py
Replace this with a summary of your changes including any high-level business or decision-making context.
- 🌐 Release (for preparing a release branch)
- 🔄 Refactor (for code refactoring and tech debt)
- Call out here if this is dependent on another Pull Request, and paste the link if possible
- This branch contains a breaking change ⚠️
=> Chat testing

src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/static/js/manage_organization.js
- Fix text display issues caused by HTML linting
- Restore overwritten Javascript that was causing orders dropdown to remain open
=> Bugfix/issue 224/orders reviews text and dropdown bug fix

src/donor_dashboard/templates/donor_dashboard/statistics.html, src/donor_dashboard/tests.py, src/donor_dashboard/views.py, src/recipient_dashboard/templates/recipient_dashboard/recipient_statistics.html, src/recipient_dashboard/tests.py, src/recipient_dashboard/views.py, src/static/css/statistics.css, src/static/js/org_statistics.js, src/static/js/user_statistics.js
- Add tooltips with more detailed descriptions to charts
- Increase readability of date formatted tick labels
- Improve readability of legends and axis labels
=> Chore/issue 236/improve statistics page for clarity (tooltips/labels/legends)

src/accounts/tests.py
Adds testing for accounts sub application
=> accounts testing

src/donor_dashboard/templates/donor_dashboard/list.html, src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/static/js/manage_organization.js
Fix to "Delete buttons not working in organization page"
- None
=> Bugfix/issue 234/delete buttons not working in org page

.github/workflows/branch-name-check.yml, src/messaging/tests.py, src/messaging/views.py
Implement test cases for messaging functionality views
=> Tests/issue 262/implement test cases for messaging functionality views

src/accounts/templates/accounts/landing.html, src/accounts/templates/accounts/login.html, src/donor_dashboard/forms/__init__.py, src/donor_dashboard/forms/add_donation_form.py, src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/views.py, src/static/css/manage_organization.css, src/static/js/manage_organization.js, src/templates/_base.html
Add frontend verification messages for `Quantity` and `Pickup By` fields in the add donation form.
=> Feature/issue 244/frontend verification for fields in add donation

src/recipient_dashboard/tests.py, src/recipient_dashboard/views.py
Implemented the limitation to 3 quantity limit of the same item, and 5 different items pending pick up at a time, and added test cases for them!
None.
=> implemented order limitations and added tests

src/recipient_dashboard/templates/recipient_dashboard/dashboard.html
removed auto location grab from the user, and made it only triggered when you hit use my location. 
None.
=> Bugfix/issue 204/only use location when button clicked

.github/ISSUE_TEMPLATE/bug-report.md
Added template for bug reporting
=> Added template for bug reporting

.github/ISSUE_TEMPLATE/feature-suggestion.md
Added feature suggestion github issue template
=> Added feature suggestion github issue template

src/user_profile/templates/user_profile/profile.html
Fix the phone number field in the profile page
- None
=> fix phone number field in profile page

src/donor_dashboard/views.py, src/user_profile/templates/user_profile/profile.html
mark as pending or mark as complete is giving error page
- None
=> Bugfix/issue 294/mark as pending or mark as complete is giving error page

src/recipient_orders/tests.py
Added testing coverage for modifying orders. 
None.
=> Increase test coverage for modifying orders

src/accounts/tests.py, src/accounts/views.py
- Adds in a check to see what field is providing error in register view
- Also adds in several other confirmations
- Adds tests
=> bug fix for better register warnings

src/user_profile/views.py
- Adds checks / validation into the profile page for phone number and first/last name.
=> Validations for profile page

src/user_profile/templates/user_profile/profile.html
- Show placeholder if phone number is None
- Get rid of red text.
=> Fix user profile issues - Phone Number None

src/user_profile/tests.py
Updating failing test case to resolve the Build Failure
=> Updating failing test case to resolve the Build Failure

src/messaging/templates/messaging_dashboard.html, src/messaging/tests.py, src/messaging/urls.py, src/messaging/views.py, src/static/js/messaging.js
=> messaging using ajax

src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/static/js/manage_organization.js
- Disallow names of 0 length or greater than 250 character length.
- Donation quantity must be between 1 and 200
- DAte must be between tomorrow and 1 week from today
- Also fixes the date issue by normalizing for hour of day
=> Add/Modify Donation updates to validation/restrictions

src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/views.py
Orders now sorted based on pickup date with recent orders showing first
=> Orders now sorted based on pickup date with recent orders showing first

src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/static/js/manage_organization.js
Fixes bug where the date warning was appearing when the pickup date for a new donation was set to today
=> bugfix/issue 293/frontend pickup date fix

src/donor_dashboard/templates/donor_dashboard/manage_organization.html
Add created time in donation cards
- None
=> add created time in donation cards

src/donor_dashboard/templates/donor_dashboard/list.html, src/donor_dashboard/templates/donor_dashboard/manage_organization.html, src/donor_dashboard/templates/donor_dashboard/statistics.html, src/static/css/tooltips.css, src/static/js/org_list_tabs.js
Improve organization list UI for better consistency
- Truncate organization titles when they overflow two lines
- Change organization type to display an icon instead of text
=> Bugfix/issue 296/organization cards inconsistent UI

src/django_management/settings.py, src/django_management/urls.py, src/instructions/admin.py, src/instructions/apps.py, src/instructions/models.py, src/instructions/templates/instructions/instructions.html, src/instructions/tests.py, src/instructions/urls.py, src/instructions/views.py, src/templates/partials/theader.html
- Adds a permalink to the instructions in the header tab
- Creates the instructions page with tabs for donor, recipient, and community drives
- Populates instruction information
--
--
--
=> Create instructions app
